name: Bare Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

env: 
  conda_env: CaverNG

jobs:
  BareTests:
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
        python-version: 
          - "3.10"
          - "3.11"
          - "3.12" # control
          # - "3.13"
          # - "3.14"
        pymol-tag:
          - 'latest pymol open source'
        conda-channel:
          - -c conda-forge
        pymol-version:
          - "pymol-open-source"

        java: [ '8', '11' , '21']

        # include:
          # windows
          # - os: windows-latest
          #   python-version: "3.11"
          #   pymol-tag: 'latest pymol open source'
          #   conda-channel: -c conda-forge
          #   pymol-version: "pymol-open-source"

          # macos latest, latest pymol open source and py312
          # - os: macos-15
          #   python-version: "3.12"
          #   pymol-tag: 'latest pymol open source'
          #   pymol-version: "pymol-open-source"
          #   conda-channel: -c conda-forge

          # # macos tahoe, latest pymol open source and py312
          # - os: macos-26
          #   python-version: "3.12"
          #   pymol-tag: 'latest pymol open source'
          #   pymol-version: "pymol-open-source"
          #   conda-channel: -c conda-forge


          # # ubuntu arm 
          # not available for private repos
          # - os: ubuntu-24.04-arm
          #   python-version: "3.12"
          #   pymol-tag: 'latest pymol open source'
          #   pymol-version: "pymol-open-source"
          #   conda-channel: -c conda-forge
          
          # # latest bundled pymol 
          # - os: ubuntu-latest
          #   python-version: "3.10"
          #   pymol-tag: 'latest pymol bundle'
          #   pymol-version: "pymol-bundle"
          #   conda-channel: -c schrodinger -c conda-forge

          # # bundled pymol, v2
          # - os: ubuntu-latest
          #   python-version: "3.11"
          #   pymol-tag: 'legacy (v2) pymol bundle'
          #   pymol-version: "pymol-bundle<3"
          #   conda-channel: -c schrodinger -c conda-forge
            
          
          # # pymol-open-source, v2 py310
          # - os: ubuntu-latest
          #   python-version: "3.10"
          #   pymol-tag: 'legacy (v2) pymol open source'
          #   pymol-version: "pymol-open-source<3"
          #   conda-channel: -c conda-forge

          # # pymol-open-source, v2 py311
          # - os: ubuntu-latest
          #   python-version: "3.11"
          #   pymol-tag: 'legacy (v2) pymol open source'
          #   pymol-version: "pymol-open-source<3"
          #   conda-channel: -c conda-forge
            



    runs-on: ${{ matrix.os }}
    # set time limits according to the runner os. 
    # if the runner os is windows, set it to 60,
    # otherwise, set it to 35
    timeout-minutes: ${{ matrix.os == 'windows-latest' && 60 || 35 }}


    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}
      DISPLAY: ':99.0'

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: setup Qt headless Display on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          make setup-display-gha


      - name: setup Qt headless Display on Windows
        if: startsWith(matrix.os, 'windows')
        uses: pyvista/setup-headless-display-action@v2
      
      - name: Setup Conda on ${{ matrix.os }} 
        uses: conda-incubator/setup-miniconda@v3
        with:
            auto-update-conda: false
            activate-environment: ${{ env.conda_env }}
            auto-activate-base: false
            python-version: ${{ matrix.python-version }}
            conda-solver: libmamba

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      
      - name: Setup PyMOL - (${{ matrix.pymol-tag }})-(${{ matrix.os }}-py${{ matrix.python-version }})
        run: |
          conda install ${{ matrix.conda-channel}} '${{ matrix.pymol-version}}' pyqt=5 -n ${{ env.conda_env }} -y
          conda info
          conda list
          which python
          which python3
    

      - name: Full Unit Test on Ubuntu
        run: |
          python -m pip install -r Caver4/requirements/plotter.txt
          make prepare-test
          make test || make test-faulthandler
      
      # - name: Convert coverage report to XML for codecov
      #   run: |
      #     coverage xml

      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     files: ./coverage.xml
      #     env_vars: OS,PYTHON
      #     fail_ci_if_error: false
      #   env:
      #     CODECOV_TOKEN: 

      # - name: Clean up
      #   run: |
      #     make clean